{
 "title": "Inventory API Dashboard",
 "time": { "from": "2025-11-18T10:52:28.622Z", "to": "2025-11-18T10:54:37.016Z" },
 "panels": [
  {
   "title": "Total de requests acumulados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(inventory_http_requests_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (HTTP 500)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(inventory_http_requests_total{http_status=\"500\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia P95 por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(inventory_request_duration_seconds_bucket[5m])) by (le, endpoint)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests por endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(inventory_http_requests_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}